defaultSemverRangePrefix: ""

enableInlineHunks: true

enableScripts: true

enableTelemetry: false

nodeLinker: node-modules

packageExtensions:
  "@chakra-ui/progress@*":
    dependencies:
      "@chakra-ui/styled-system": "*"
  "@chakra-ui/react@*":
    dependencies:
      "@chakra-ui/styled-system": "*"
  "@chakra-ui/toast@*":
    dependencies:
      "@chakra-ui/styled-system": "*"
  "@remix-run/dev@*":
    dependencies:
      react: "*"
      react-dom: "*"
  "@remix-run/node@*":
    dependencies:
      react: "*"
      react-dom: "*"
  ts-node-dev@*:
    dependencies:
      "@types/node": "*"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
    spec: "@yarnpkg/plugin-version"
  - path: .yarn/plugins/@yarnpkg/plugin-constraints.cjs
    spec: "@yarnpkg/plugin-constraints"
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"

preferInteractive: true

yarnPath: .yarn/releases/yarn-3.2.2.cjs
